---
name: Shared - Continuous Integration for common tasks

on: # yamllint disable-line rule:truthy
  workflow_call:

permissions: {}

jobs:
  linter:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/linter.yml@624be17604ee0a7378488191aacb35851e7cf001 # 0.37.1
    permissions:
      actions: read
      contents: read
      issues: write
      packages: read
      pull-requests: write
      security-events: write
      statuses: write
    with:
      codeql-languages: "" # FIXME: Let default value when CodeQL will be available (paid feature)

  build-ci:
    uses: hoverkraft-tech/ci-github-container/.github/workflows/docker-build-images.yml@c9088e8447c5a8be45157e17701023fc50ccb1c0 # 0.37.2
    permissions:
      contents: read
      packages: write
      issues: read
      pull-requests: read
      id-token: write
    with:
      oci-registry: ${{ vars.OCI_REGISTRY }}
      sign: false
      images: |
        [
          {
            "name": "backend-ci",
            "context": ".",
            "dockerfile": "./docker/backend/Dockerfile",
            "target": "ci",
            "platforms": ["linux/amd64"]
          },
          {
            "name": "frontend-ci",
            "context": ".",
            "dockerfile": "./docker/frontend/Dockerfile",
            "target": "ci",
            "platforms": ["linux/amd64"]
          },
          {
            "name": "live-data-generator-ci",
            "context": ".",
            "dockerfile": "./docker/live-data-generator/Dockerfile",
            "target": "ci",
            "platforms": ["linux/amd64"]
          },
          {
            "name": "backend",
            "context": ".",
            "dockerfile": "./docker/backend/Dockerfile",
            "target": "prod",
            "platforms": ["linux/amd64"]
          },
          {
            "name": "frontend",
            "context": ".",
            "dockerfile": "./docker/frontend/Dockerfile",
            "target": "prod",
            "platforms": ["linux/amd64"]
          },
          {
            "name": "live-data-generator",
            "context": ".",
            "dockerfile": "./docker/live-data-generator/Dockerfile",
            "target": "prod",
            "platforms": ["linux/amd64"]
          }
        ]
    secrets:
      oci-registry-password: ${{ secrets.GITHUB_TOKEN }}

  continuous-integration:
    name: Continuous Integration - ${{ matrix.application }}
    uses: hoverkraft-tech/ci-github-nodejs/.github/workflows/continuous-integration.yml@df348077afa4e79725151d50606e9dc63f86dcb6 # 0.24.4
    needs: build-ci
    permissions:
      contents: read
      id-token: write
      pull-requests: write
      security-events: write
      packages: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - application: backend
            image: backend-ci
            path: ./application/monitoring-workspace/backend
          - application: frontend
            image: frontend-ci
            path: ./application/monitoring-workspace/frontend
          - application: live-data-generator
            image: live-data-generator-ci
            path: ./application/live-data-generator
    with:
      working-directory: /usr/src/app
      container: |
        {
          "image": ${{ toJSON(fromJSON(needs.build-ci.outputs.built-images)[matrix.image].images[0]) }},
          "credentials": {
            "username": ${{ toJson(github.repository_owner) }}
          },
          "pathMapping": {
            "/usr/src/app": "${{ matrix.path }}"
          }
        }
      code-ql: "" # FIXME: Set `typescript` when CodeQL will be available (paid feature)
      dependency-review: false # FIXME: Set `true` when Dependency Review will be available (paid feature)
    secrets:
      container-password: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: continuous-integration
    uses: hoverkraft-tech/ci-github-container/.github/workflows/docker-build-images.yml@c9088e8447c5a8be45157e17701023fc50ccb1c0 # 0.37.2
    permissions:
      contents: read
      packages: write
      issues: read
      pull-requests: read
      id-token: write
    with:
      oci-registry: ${{ vars.OCI_REGISTRY }}
      sign: false
      images: |
        [
          {
            "name": "backend",
            "context": ".",
            "dockerfile": "./docker/backend/Dockerfile",
            "target": "prod",
            "platforms": ["linux/amd64"]
          },
          {
            "name": "frontend",
            "context": ".",
            "dockerfile": "./docker/frontend/Dockerfile",
            "target": "prod",
            "platforms": ["linux/amd64"]
          },
          {
            "name": "live-data-generator",
            "context": ".",
            "dockerfile": "./docker/live-data-generator/Dockerfile",
            "target": "prod",
            "platforms": ["linux/amd64"]
          }
        ]
    secrets:
      oci-registry-password: ${{ secrets.GITHUB_TOKEN }}

  tests-charts:
    name: Tests - Charts
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: read
      packages: read
    steps:
      - name: Test helm charts
        uses: hoverkraft-tech/ci-github-container/actions/helm/test-chart@c9088e8447c5a8be45157e17701023fc50ccb1c0 # 0.37.2
        with:
          helm-set: |
            backend.image=${{ fromJSON(needs.build.outputs.built-images).backend.images[0] }}
            frontend.image=${{ fromJSON(needs.build.outputs.built-images).frontend.images[0] }}
            live-data-generator.api.image=${{ fromJSON(needs.build.outputs.built-images)['live-data-generator'].images[0] }}
            live-data-generator.ui.image=${{ fromJSON(needs.build.outputs.built-images)['live-data-generator'].images[0] }}
            global.imagePullSecrets[0].name=regcred
          oci-registry: ${{ vars.OCI_REGISTRY }}
          oci-registry-password: ${{ github.token }}
