---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: __APP_NAME__-uat
  namespace: argocd
  annotations:
    argocd.argoproj.io/application-repository: __APP_NAME__
    argocd.argoproj.io/environment: "uat"
    argocd.argoproj.io/sync-wave: "1"
  labels:
    layer: applications
    service: __APP_NAME__
    component: main
    environment: uat
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: __APP_NAME__-uat
    server: https://prod.example.com
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: ghcr.io/hoverkraft-sh/__APP_NAME__/charts/application
      targetRevision: "" # Will be updated by deploy workflow
      chart: __APP_NAME__
      helm:
        values: |
          ingress:
            enabled: true
            className: "traefik"
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
            hosts:
              - host: __APP_NAME__-uat.example.com
                paths:
                  - path: /
                    pathType: ImplementationSpecific
            tls:
              - secretName: __APP_NAME__-tls
                hosts:
                  - __APP_NAME__-uat.example.com
