---
name: Internal - Main - Continuous Integration

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
    tags: ["*"]

  schedule:
    - cron: "25 8 * * 1"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/__shared-ci.yml
    permissions:
      actions: read
      contents: read
      issues: write
      packages: read
      pull-requests: write
      security-events: write
      statuses: write
