apiVersion: v1
kind: Namespace
metadata:
  name: cicada-sense-production
  annotations:
    app.kubernetes.io/instance: cicada-sense-production
    argocd.argoproj.io/sync-options: Prune=true
    argocd.argoproj.io/sync-wave: "0"
