# commons manifests (no argocd apps) that will be deployed into all clusters
# will apply `./commons` folder
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: commons
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
    - list:
        elements:
          - cluster: tools
            url: https://kubernetes.default.svc
            env: tools
          - cluster: dev
            url: https://dev.example.com
            env: dev
          - cluster: prod
            url: https://prod.example.com
            env: prod
  template:
    metadata:
      name: commons-{{env}}
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "2"
      labels:
        layer: infrastructure
        service: commons
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      destination:
        namespace: default
        server: "{{url}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - SkipDryRunOnMissingResource=true
        automated:
          prune: true
          selfHeal: true
      sources:
        # NOTE: please change the organization and repository name here
        - repoURL: git@github.com:hoverkraft-sh/argocd-app-of-apps.git
          targetRevision: HEAD
          path: commons
          directory:
            recurse: true
