apiVersion: v1
kind: Namespace
metadata:
  name: __APP_NAME__-production
  annotations:
    app.kubernetes.io/instance: __APP_NAME__-production
    argocd.argoproj.io/sync-options: Prune=true
    argocd.argoproj.io/sync-wave: "0"
