---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicada-sense-production
  namespace: argocd
  annotations:
    argocd.argoproj.io/application-repository: cicada-sense
    argocd.argoproj.io/environment: "production"
    argocd.argoproj.io/sync-wave: "1"
  labels:
    layer: applications
    service: cicada-sense
    component: main
    environment: prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: cicada-sense-production
    server: https://prod.example.com
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: ghcr.io/<organization>/cicada-sense/charts/application
      targetRevision: "" # Will be updated by deploy workflow
      chart: cicada-sense
      helm:
        values: |
          backend:
            ingress:
              enabled: true
              className: "traefik"
              hosts:
                - host: cicada-sense.<user-xx>.hoverkraft.cloud
                  paths:
                    - path: /api
                      pathType: Prefix
                    - path: /socket.io
                      pathType: Prefix
          frontend:
            ingress:
              enabled: true
              className: "traefik"
              hosts:
                - host: cicada-sense.<user-xx>.hoverkraft.cloud
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
          live-data-generator:
            api:
              ingress:
                enabled: true
                className: "traefik"
                hosts:
                  - host: cicada-sense-generator.<user-xx>.hoverkraft.cloud
                    paths:
                      - path: /api
                        pathType: Prefix
            ui:
              ingress:
                enabled: true
                className: "traefik"
                hosts:
                  - host: cicada-sense-generator.<user-xx>.hoverkraft.cloud
                    paths:
                      - path: /
                        pathType: Prefix
